name: Generate Resume

on:
  push:
    paths:
      - 'resume/resume.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install pdfkit python-docx

      - name: Generate Resume
        run: python scripts/generate_resume.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add resume/*
          git commit -m "Updated resume files" || echo "No changes to commit"
          git push
